[server.ty]
command = "ty"
args = ["server"]

[language.python]
servers = ["ty"]

[server.tsserver]
command = "typescript-language-server"
args = ["--stdio"]

[language.javascript]
servers = ["tsserver"]
